- name: tempating istio-gw-install scripts
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{item}}.sh"
  with_items:
    - install_istio_ingres_gw

- name: install istio gateway
  shell: sh /tmp/install_istio_ingres_gw.sh

- name: Creating secure ingress gw secret
  shell: 
    cmd: |
      cat <<EOF | kubectl apply -f -
      apiVersion: v1
      kind: Secret
      metadata:
        name: ingress-gw-ssl
        namespace: "{{ istio_namespace}}"
      data:
        ca.crt: ""
        tls.crt: "{{ ssl_site_crt | b64encode }}"
        tls.key: "{{ ssl_site_key | b64encode }}"
      EOF

- name: Creating ingress gw object
  shell: 
    cmd: |
      cat <<EOF | kubectl apply -f -
      apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      metadata:
        name: sbrc-gateway
        namespace: "{{ istio_namespace}}"
      spec:
        selector:
          istio: ingressgateway
        servers:
        - port:
            number: 443
            name: https
            protocol: HTTPS
          tls:
            mode: PASSTHROUGH
          hosts:
          - "{{domain_name}}"
      EOF


- name: Creating virtual service object
  shell: 
    cmd: |
      cat <<EOF | kubectl apply -f -
      apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      metadata:
        name: vsnginxingress
        namespace: "{{ namespace}}"
      spec:
        hosts:
        - "{{domain_name}}"
        gateways:
        - "{{ istio_namespace}}/sbrc-gateway"
        tls:
        - match:
          - port: 443
            sniHosts: 
            - "{{domain_name}}"
          route:
          - destination:
              port:
                number: 443
              host: nginx-ingress.{{ namespace }}.svc.cluster.local
      EOF

