---
# tasks file for istio
- name: tempating variables
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{item}}.yaml"
  with_items:
    - istio

- name: helm install istio-base
  shell: helm upgrade --install --atomic --timeout {{helm_install_timeout | d("10m")}} istio-base istio/base  --kube-context {{item}} -n {{namespace}} --create-namespace --wait 10
  loop: "{{ctx_clusters}}"

- name: helm install istiod
  shell: helm upgrade --install --atomic --timeout {{helm_install_timeout | d("10m")}} istiod istio/istiod  --kube-context {{item}} -n {{namespace}} --create-namespace --wait 30
  loop: "{{ctx_clusters}}"

- name: Get the deployment rollout status
  shell: "kubectl get deployments -A | grep -i istiod | if [[ $(wc -l) > 0 ]]; then awk '{print $3}' | awk -F/ '{if ($1 ~ $2){exit 0} else {exit 1}}'; else exit 1; fi"
  args:
    executable: /bin/bash
  register: deployment_result
  ignore_errors: true

- name: fail when deployment are not successful
  fail:
    msg: "Unable to get success status for any of these - deployment,"
  when:  deployment_result.rc != 0