---
# tasks file for istio
- name: tempating variables
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{item}}.yaml"
  with_items:
    - istio


- name: add istio helm repo
  shell: helm repo add istio {{istio_chart_repo}}


- name: update repo
  shell: helm repo update

- name: helm install istio-base
  shell: kubectl config use-context {{item}} &&  helm upgrade --install --atomic --timeout {{helm_install_timeout | d("10m")}} istio-base istio/base -n istio-system --create-namespace --set defaultRevision=default --wait
  loop: "{{ctx_clusters}}"

- name: helm install istiod
  shell: kubectl config use-context {{item}} &&  helm upgrade --install --atomic --timeout {{helm_install_timeout | d("10m")}} istiod istio/istiod  -n istio-system --create-namespace --wait
  loop: "{{ctx_clusters}}"
