---
# tasks file for istio
- name: tempating variables
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{item}}.yaml"
  with_items:
    - istio


- name: add istio helm repo
  shell: helm repo add istio {{istio_chart_repo}}


- name: update repo
  shell: helm repo update

- name: helm install istio-base
  shell: kubectl config use-context {{item}} && helm install istio-base istio/base -n {{namespace}} --create-namespace --set defaultRevision=default --wait 10
  loop: "{{ctx_clusters}}"

- name: helm install istiod
  shell: kubectl config use-context {{item}} && helm install istiod istio/istiod  -n {{namespace}} --create-namespace --wait
  loop: "{{ctx_clusters}}"
