apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.dockerhub }}/{{ .Values.repository }}:{{ .Values.image_tag }}"
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config
        ports:
        - containerPort: {{ .Values.network.port_api }}
        - containerPort: {{ .Values.network.port_transport }} 
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: api-{{ .Chart.Name }}
    protocol: TCP
    port: {{ .Values.network.targetport_api }}
  - name: transport-{{ .Chart.Name }}
    protocol: TCP
    port: {{ .Values.network.targetport_transport }}
  selector:
    app: {{ .Chart.Name }}