namespace: dev
imagepullsecrets: 
dockerhub: dockerhub

replicaCount: 1
repository: sunbird-rc-claim-ms
image_tag: v0.0.13
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
network:
  port: 8082
  targetport: 8082
strategy:
  type: RollingUpdate
  maxsurge: 50%
  maxunavailable: 50%

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 

claim_msenv:
  connectionInfo_uri: jdbc:postgresql://postgres-cluster-rw.cnpg:5432/registry
  connectionInfo_username: registry
  connectionInfo_password: admin134
  sunbirdrc_url: http://registry:8081
