---
- name: Create Network
  collections: 
    - oracle.oci
  hosts: localhost
  vars:
    vcn_cidr_block: "10.0.0.0/16"
    vcn_name: "sunbird-vcn"
    vcn_dns_label: "sunbirdvcn"
    compartment_id: "{{ lookup('env', 'SAMPLE_COMPARTMENT_OCID') }}"
    quad_zero_route: "0.0.0.0/0"

  tasks: 
  - name: Check pre-requisites
    fail:
      msg: "Environment variable {{item}} not set. Please declare an environment variable with an appropriate value for the sample to work."
    when: item not in ansible_env
    with_items:
      - "SAMPLE_COMPARTMENT_OCID"

  - name: Create a VCN
    oci_network_vcn:
      compartment_id: "{{ compartment_id }}"
      display_name: "{{ vcn_name }}"
      cidr_block: "{{ vcn_cidr_block }}"
      dns_label: "{{ vcn_dns_label }}"
    register: result
    tags:
      - network

  - set_fact:
      vcn_id: "{{ result.vcn.id }}"
      vcn: "{{ result.vcn }}"
      cacheable: yes
    tags:
      - network

  - name: Get availability domains for vlans
    oci_identity_availability_domain_facts:
      compartment_id: "{{compartment_id}}"
    register: oci_ads
    tags:
      - always

  - set_fact:
      availability_domain: "{{oci_ads.availability_domains[0].name}}"
    tags:
      - always

  - name: Create a new Internet Gateway
    oci_network_internet_gateway:
      compartment_id: "{{ compartment_id }}"
      vcn_id: "{{ vcn_id }}"
      name: "sunbird-igw"
      is_enabled: 'yes'
      state: 'present'
    register: result
    tags:
      - network

  - set_fact:
      ig_id: "{{ result.internet_gateway.id }}"
      route_table_rules:
        - cidr_block: "{{ quad_zero_route }}"
          network_entity_id: "{{ ig_id }}"
    tags:
      - network

  - name: Create route table to connect internet gateway to the VCN
    oci_network_route_table:
      compartment_id: "{{ compartment_id }}"
      vcn_id: "{{ vcn_id }}"
      name: "public route table"
      route_rules: "{{ route_table_rules }}"
      state: 'present'
    register: result
    tags:
      - network

  - set_fact:
      rt_id: "{{ result.route_table.id }}"
    tags:
      - network