---
# tasks file for bootstrap-k8s

- hosts: local
  gather_facts: false
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
    CTX_CLUSTER1: "{{ctx_cluster1}}"
    CTX_CLUSTER2: "{{ctx_cluster2}}"
    OCI_CLI_AUTH: instance_principal
  vars_files:
    - "{{inventory_dir}}/secrets.yaml"
  tasks:
    - name: Creating namespace
      shell: "kubectl create namespace istio-system --context={{item}}"
      ignore_errors: yes
      loop: "{{ctx_clusters}}"
