---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-default
  namespace: {{ .Values.namespace }}
data:
{{ tpl (.Files.Glob "proxy-default.conf compression.conf").AsConfig .| indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Values.namespace }}
data:
{{ tpl (.Files.Glob "nginx.conf").AsConfig .| indent 2 }}