---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-default
  namespace: {{ .Values.namespace }}
data:
  proxy-default.conf: |-
{{ tpl (.Files.Glob "config/proxy-default.conf") .| indent 4}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Values.namespace }}
data:
{{ tpl (.Files.Glob "config/nginx.conf").AsConfig .| indent 2 }}