---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-default
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "config/compression.conf").AsConfig | indent 2 }}
{{ (.Files.Glob "config/proxy-default.conf").AsConfig | indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "config/nginx.conf").AsConfig | indent 2 }}