---
postgresql_user: postgres
postgresql_auth_method: "{{ ansible_fips  | ternary('scram-sha-256', 'md5') }}"
postgres_users_no_log: true
postgresql_unix_socket_directories:
  - /var/run/postgresql

############# Postgres users and databases ###############
postgresql_users:
  - name: postgres
    login_password: "{{core_vault_dp_pgdb_password}}"
    password: "{{core_vault_dp_pgdb_password}}"
    db: registry
    login_user: postgres
    priv: "ALL"

postgresql_databases:
  - name: registry
    login_password: "{{core_vault_dp_pgdb_password}}"
    owner: "postgres"
    login_user: postgres

