core_vault_dp_pgdb_password: "postgres"
core_vault_postgres_password: "postgres"
core_vault_postgres_username: "postgres"

postgres:
  db_url: "{{ groups['postgres'][0] }}"
  db_username: postgres
  db_name: registry
  db_password: "{{core_vault_dp_pgdb_password}}"
  db_port: 5432
  db_admin_user: postgres
  db_admin_password: "{{core_vault_postgres_password}}"

postgresql_users:
  - name: postgres
    login_password: "{{core_vault_dp_pgdb_password}}"
    password: "{{core_vault_dp_pgdb_password}}"
    db: registry
    login_user: postgres
    priv: "ALL"

postgresql_databases:
  - name: registry
    login_password: "{{core_vault_dp_pgdb_password}}"
    owner: "postgres"
    login_user: postgres

postgres_users_no_log: false