env: dev
namespace: "{{ env }}"
bootstrap_namespace: "{{ namespace }}"
kubeconfig_path: /home/ubuntu/istio-multicluster-setup/devops/istio-samples/multi-primary-diff-nw-oci/terraform/modules/oke/generated/oke_cluster1
domain_name: istio.multi.sunbirdrc.app.oci
nginx_public_ingress_type: ClusterIP   ### or LoadBalancer
oci_tenancy_ocid: "ocid1.tenancy.oc1..aaaaaaaa"
region: ""

# The proxy key and crt values should be padded to the right by a couple of spaces 
# Example:
# ssl_site_key: |+
#    -----BEGIN PRIVATE KEY-----
#    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDFrWgCrQPHcZ2I
#    UqvtIOY5lxlgU22+4BQbjMRN6NZn89AfWMUpRQOCoohPpTs0/JF+a20RI256gNkr
#    yxm5BleKMv9dovAUjPElrdsWsBq9XOFDzN7GJnWpyB7oFYOoqrbRNrvL/dTP/op/
#    -----END PRIVATE KEY-----

ssl_site_key: |+

ssl_site_crt: |+


CERTIFICATE_PUBLIC_KEY: |+


CERTIFICATE_PRIVATE_KEY: |+


sunbird_rc:
  elasticsearch_enabled: false


filestorage:
  minio_root_user: admin
  minio_root_password: admin1234

admin_api_secret: change.my.password

### Applicable only if nginx_public_ingress_type: LoadBalancer
nginx_ingress_service_annotations:
  service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
  service.beta.kubernetes.io/oci-load-balancer-internal: "false"
  service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10Mbps"
  service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100Mbps"
  service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.adfalk"


postgress_db_host: postgres-cluster-rw.{{namespace}}
postgres_connectionInfo_uri: "jdbc:postgresql://postgres-cluster-rw.{{namespace}}:5432/registry"
postgres_connectionInfo_username: registry
postgres_connectionInfo_password: admin134

longhorn_default_replica_count: 2

search_provider_name: ""
