env: dev 
namespace: "{{ env }}" 
bootstrap_namespace: "{{ namespace }}"
kubeconfig_path: /home/ubuntu/secrets/k8s.yaml

core_vault_dp_pgdb_password: "postgres"
core_vault_postgres_password: "postgres"
core_vault_postgres_username: "postgres"

# The proxy key and crt values should be padded to the right by a couple of spaces 
# Example:
# ssl_site_key: |+
#    -----BEGIN PRIVATE KEY-----
#    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDFrWgCrQPHcZ2I
#    UqvtIOY5lxlgU22+4BQbjMRN6NZn89AfWMUpRQOCoohPpTs0/JF+a20RI256gNkr
#    yxm5BleKMv9dovAUjPElrdsWsBq9XOFDzN7GJnWpyB7oFYOoqrbRNrvL/dTP/op/
#    -----END PRIVATE KEY-----
ssl_site_key: |+

ssl_site_crt: |+


postgres:
  db_url: "{{ groups['postgres'][0] }}"
  db_username: postgres
  db_name: registry
  db_password: "{{core_vault_dp_pgdb_password}}"
  db_port: 5432
  db_admin_user: postgres
  db_admin_password: "{{core_vault_postgres_password}}"

postgresql_users:
  - name: postgres
    login_password: "{{core_vault_dp_pgdb_password}}"
    password: "{{core_vault_dp_pgdb_password}}"
    db: registry
    login_user: postgres
    priv: "ALL"

postgresql_databases:
  - name: registry
    login_password: "{{core_vault_dp_pgdb_password}}"
    owner: "postgres"
    login_user: postgres

postgres_users_no_log: false


certificateapi_enabled: true
certificatesign_enabled: false
claim_ms_enabled: false
elasticsearch_enabled: false
filestorage_enabled: false
keycloak_enabled: false
registry_enabled: true