imagepullsecrets: 
dockerhub: dockerhub

replicaCount: 1
repository: sunbird-rc-keycloak
image_tag: latest
resources:
  requests:
    cpu: '100m'
    memory: '100Mi'
  limits:
    cpu: '1000m'
    memory: '1024Mi'
network:
  port: 8080
  targetport: 8080
strategy:
  type: RollingUpdate
  maxsurge: '50%'
  maxunavailable: '50%'

autoscaling:
  enabled: 'false'
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: ''

keycloakenv:
  DB_PASSWORD: admin134
  KEYCLOAK_PASSWORD: password
  KEYCLOAK_LOGO: https://svgshare.com/i/hCs.svg
  DB_VENDOR: 'postgres'
  DB_ADDR: postgres-cluster-rw.cnpg
  DB_PORT: '5432'
  DB_DATABASE: 'registry'
  DB_USER: registry
  KEYCLOAK_USER: admin
  PROXY_ADDRESS_FORWARDING: 'true'
  KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
  DOMAIN_NAME: "istio.sunbirdrc.app.oci"
  ADMIN_API_SECRET: kalfdkjakaldskfjalsdjfl