---
#######################  SUnbird RC Variables ########################
postgres_connectionInfo_uri: "jdbc:postgresql://{{ application_postgres_host }}:5432/registry"
postgres_connectionInfo_username: "{{core_vault_postgres_username}}"
connectionInfo_password: "{{ core_vault_postgres_password }}"
elastic_search_connection_url: "{{ groups['es']|join(':9200,')}}:9200"
#############################################################################
